name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Failure
        run: |
          echo "Hello World NOT!"
          exit 1