name: PULL REQUEST

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: |
          echo "Hello World!"
          exit 1
          
