name: PULL REQUEST

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup, Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3
      - name: Success
        run: |
          echo "Hello World!"
